### ISSUE TITLE
Layout export: cannot export implied links in split models

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#141]
This issue is about the split models (#56).

Exporting "implied links" means that when the user references two nodes (classes/states) in a layout diagram description which two nodes have a link (association/transition) between them, then the link is automatically shown on the diagram.

The source of the problem is the same as the one described in #57 (cannot see associations from their ends at Java runtime).

**Comment by kovacsgabor** [comment]
A possible solution to this issue is to introduce JDT in the layout exportation as well.

**Comment by devaigergely81** [comment]
Since the first step of the visualization process is UML model generation (already via JDT), it would be good to reuse that phase instead of a separate walk-through of the model. It already generates the mapping from class names representing states and transitions (for animation). Something similar could be done to list associations. It could also be used for runtime validation as noted in #57.

**Comment by kovacsgabor** [comment]
It is possible to reuse that information but it requires the modification of export.uml2 which is not achievable until the end of November. I will create a quick solution which will parse the model one more time to get the required information. A faster solution should be implemented in the future.

**Comment by kovacsgabor** [comment]
The quick and dirty solution is implemented for v0.3.0 in commit 868eded.

**Comment by devaigergely81** [comment]
Since this is already solved, I close this and propose opening a new refactoring issue proposing a better solution.
