### ISSUE TITLE
No wizard to create XtxtUML files

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#181]
Currently, we have no wizard to create files with extension ```.xtxtuml``` other than a ```model-info.xtxtuml```.

**Comment by nboldi** [comment]
There should be wizards for model class, association, signal, etc...

**Comment by devaigergely81** [comment]
For the moment, I have written in the documentation how to create model elements by creating a new file with appropriate extension: http://txtuml.inf.elte.hu/wiki/doku.php?id=v030:userguide#new_model_elements

We have to think about the wizards proposed above, because the users will not always want to create a new file for each model element...
