### ISSUE TITLE
Is cpp runtime really optional?

### ISSUE THREAD

**Issue by gerazo** [ELTE-Soft/txtUML#231]
What should we generate if there is no runtime? Only skeleton code? In the latter case the runtime present is also not a problem.

**Comment by gerazo** [comment]
@devaigergely81 it would be best to decide it now because we do have current issues because of this. 

Without the runtime, there cannot be any reference to initialization, configuration or any kind of working code. Furthermore unticking the runtime option not only leaves out the runtime, but changes the code generation itself which seems to be without purpose... at least the resulting code is not usable without hand editing and integrating.

I think it does not make any sense to leave the runtime out. Instead we should always add the runtime and generate code for it but decouple the runtime as much as possible leaving the possibility for the user the switch runtimes easily (even with leaving the configuration of one particular runtime intact) and implement its own runtime if it is needed.
See https://github.com/ELTE-Soft/txtUML/issues/232

**Comment by devaigergely81** [comment]
I agree with the decoupling of the runtime.
The runtime code generation is optional, because users might want to place the runtime only once somewhere in their C++ codebase and compile/link the C++ codes generated from different models with that single instance of the runtime source. We could support this by making the runtimes available for download on the txtUML website. In such a case it is annoying if the compilation of each new model pollutes the projects with writing out the runtime over and over again.

**Comment by gerazo** [comment]
Super! @nagyandras95 The decision is:
The UI option only controls the copying of the runtime files next to the generated files. The code which we generate should not change and this should always suppose that some kind of runtime is available at the place of compilation

So we should probably rephrase the option to something more meaningful, like "Add runtime to generated sources" or maybe "Copy" instead of "Add"
