### ISSUE TITLE
External class support in JtxtUML

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#254]
JtxtUML needs a full support for external classes (and later, for external data types).

Related issues: #70, #71.

**Comment by kovacsgabor** [comment]
#14 is about external class support in XtxtUML, which should be implemented after this issue is fixed.

**Comment by kovacsgabor** [comment]
A proposal for external class creation: an `@Implementation` annotation which would be applied to external classes to define an implementor class for them.

Pros:
 * `Action.create` could be used to instantiate external classes.

Cons:
 * What about constructor parameters? They would never appear in the model.

**Comment by devaigergely81** [comment]
Another proposal:
~~~~
// My1 is not visible in the model,
// but it can be placed in a model package for convenience:
@External
class My1 extendy Anything {}

// My2 is part of the model,
// but it may have externals inside:
class My2 extends ModelClass {
	// my3 is invisible in the model:
	@External
	Anything my3;

	// my4 is visible in the model:
	String my4;
	
	// my5 is invisible in the model:
	@External
	void my5(My1 m) { ... }
	
	// The signature of my6 is visible in the model,
	// but its body is not part of the model:
	@ExternalBody
	void my6(int i) { ... }
	
	// The full my7 method is part of the model,
	// its body is subject to txtUML validation:
	void my7(int i) { ... }

	// This class can have state machine:
	class Init extends Initial {}
	// ...
}
~~~~
Compilation to C++:
- External classes are discarded (they are not even part of the UML model).
- External attributes and methods are discarded.
- For ``@ExternalBody`` methods, the signature is generated in the header file, and the implementation has to be provided by the user in a separate source file.

**Comment by kovacsgabor** [comment]
I like this last proposal, although I have a question about it: What is the effect of `@External` in case of data types?

**Comment by kovacsgabor** [comment]
The previous question was specifically about the `equals`, `hashCode` and `clone` methods.

**Comment by kovacsgabor** [comment]
Another question: Isn't this dangerous to let the user declare external fields or methods of a model class which is not marked in any way? Or will it be marked in the exported model?

**Comment by gerazo** [comment]
The naming is reasonable, the syntax is still simple, I like it.

**Comment by devaigergely81** [comment]
Regarding data types: If `@External` is on the class declaration, then the whole declaration is not part of the model. The attributes and methods inside the data type declaration, which should not / cannot be visible from the model should be marked `@External` or `@ExternalBody`. I guess that `equals`, `hashCode` and `clone` will be marked in most cases, because these are not part of the model logic, but needed to ensure that data type instances are handled in accordance with value semantics. Validation rules should check for the existence of these methods in cases when they are needed.

Regarding model classes with external attributes or methods: Validation rules will ensure the consistency of the model. For example, if a method body uses an external field, either the body or the entire method should be marked as external. With this, I do not consider externals dangerous. In the exported UML model, I would *not* mark the model classes: The external attributes and methods will just not be part of the model. Methods with `@ExternalBody` will have no implementation in the UML model. This is an indication for the model compiler to generate the signatures and let the user implement them in C++. If it is considered safer, these methods could be marked somehow explicitly in the exported model.

**Comment by kovacsgabor** [comment]
And what about a class that has no methods with `@ExternalBody` annotation but some external fields which can be accessed from external methods? From the model, this class would be a simple class without any "dirty" features. At runtime, however, its instances would hold external information which could be accessed when its reference is passed to a method with an external body (in other classes).

**Comment by kovacsgabor** [comment]
Is this OK?

**Comment by kovacsgabor** [comment]
Meanwhile, another idea: `@Native` instead of `@ExternalBody?`

**Comment by kovacsgabor** [comment]
We had a discussion with @devaigergely81 about a stereotype in the exported UML2 model applied to classes which have some external features in the txtUML code, but not because of my previous concerns. It is required for (C++) code generation as the user has to have some opportunity to add these external functionalities to the exported code as well.

The idea for this in C++ is the following:
 * We generate two classes instead of one: a base class with all the modeled functionalities and a subclass which only contains the signatures of the `@ExternalBody`/`@Native` methods and constructors.
 * The user may freely modify the subclass, as it would be generated only the first time.
 * Naturally, the subclass will be instantiated by the generated code.

The stereotype will let us to omit the subclass in cases when a model class has no external functionalities.

**Comment by kovacsgabor** [comment]
Some other questions which came up on our meeting:

**Q:** What happens if the user annotates a state as external?
**A:** The state is not part of the model, therefore the model executor will simply ignore it.

**Q:** What happens if the user tries to create a transition from or to an external state?
**A:** An external state is actually not a state as it is not part of the model. Therefore this construct is invalid (unless the transition is external too but then it will be ignored as well).

**Q:** Is it possible to create external fields or methods in a signal?
**A:** _TODO_

**Comment by kovacsgabor** [comment]
The team voted for `@ExternalBody` against `@Native`.
