### ISSUE TITLE
Migrate to Mars.2

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#271]
Eclipse Mars.2 (4.5.2) is out. We should test whether txtUML is compatible with it and update the wiki page if necessary (https://github.com/ELTE-Soft/txtUML/wiki/Installation-of-the-Development-Environment).

**Comment by gerazo** [comment]
:ok:

**Comment by kovacsgabor** [comment]
According to https://www.eclipse.org/eclipse/development/plans/freeze_plan_4_5_2.php, Mars.2 only contains bug fixes, so it is intended to work without any problem with all the plugins that worked with Mars and Mars.1.

**Comment by gerazo** [comment]
It is working fine. I have updated the wiki on installation.

**Comment by djnemeth** [comment]
Shouldn't we have adjusted the target platform to Mars.2 as well?

**Comment by djnemeth** [comment]
Currently, the version constraints for dependencies of the txtUML feature (see *[feature.xml:111](https://github.com/ELTE-Soft/txtUML/blob/c94570311efb3ca1a1c8ee728cc0b6ef2daf912c/dev/features/hu.elte.txtuml.feature/feature.xml#L111)*) act as lower bounds, therefore Eclipse happily installs newer versions of the required plugins, if available. The problem is that XtxtUML is *not* fully compatible with newer versions of Xtext, and, as a result, some of its features (e.g. auto formatting) stops working in this case. The fastest solution is to modify the match rule of this dependencies to *perfect*, because in this case, Eclipse will install exactly the specified version, if available (in Mars.2, it fortunately is), and any version mismatch will result in an unresolvable conflict (see my previous comment).

In the target definition, I tried to update at least the Eclipse platform and JDT to Mars.2, but for some strange reason, integration tests in `hu.elte.txtuml.export.papyrus.tests` kept failing in this case. More surprisingly, these tests failed only during Maven builds, tests started manually from the workspace passed without problems. @dobreffandras, here are the logs: [hu.elte.txtuml.export.papyrus.IntegrationTests.txt](https://github.com/ELTE-Soft/txtUML/files/363685/hu.elte.txtuml.export.papyrus.IntegrationTests.txt)

**Comment by djnemeth** [comment]
I'm deeply confused. Apparently, Papyrus integration tests are failing even when the target platform is set to Mars.1. I have no idea why it worked last week, maybe I accidentally swapped the Maven run configs, although, I clearly remember systematically checking different target platforms and getting the results I mentioned in my previous comment. Anyway, I have opened a separate ticket for this, see #391.
