### ISSUE TITLE
Destructor support?

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#33]
ModelClass should contain a `destroy` method that is automatically called when the object is destroyed with `Action.delete`.

**Comment by devaigergely81** [comment]
This proposal raises issues, because UML has no destructors.
- UML 2.5: "A DestroyObjectAction is an Action that destroys the object [...] the Action has no other effect. In particular, no behaviors are executed, no state machine transitions are triggered, and references to the destroyed objects are unchanged."
- If we want a destructor-like operation, we have to call it in the exported UML model explicitly right before the DestroyObjectAction.
- What will happen, if the user calls the `destroy´ operation without deleting the object. I think this should be prohibited by validation.
- If all classes will have destroy operation, it will appear everywhere on the class diagrams. It will be annoying in cases when it is not used. We could solve this by adding the operation only to those classes in the UML model where the user overrides it.
- We also need to think about the termination states of state machines in this respect, once we will have support for those.

**Comment by kovacsgabor** [comment]
Adding destructor support does not change the current syntax and therefore it is not a priority to decide if we would like to implement it or not.

**Comment by kovacsgabor** [comment]
Destructor support does not seem a necessity. If it ever turns up to be required, we will come back to this topic, but until then, I close this issue.
