### ISSUE TITLE
Remove try-catch blocks from the generated JtxtUML code

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#364]
Try-catch blocks are not valid in the model.

See the vending-machine demo. For example, the entry action for ShowingPrice state is:
```
try {
       //...
      } catch (Throwable _e) {
        throw Exceptions.sneakyThrow(_e);
      }
```

**Comment by djnemeth** [comment]
Apparently, Xtext automatically appends function-wide try-catch blocks around expressions throwing unhandled checked exceptions. In the mentioned case, they're generated because of `Thread.sleep` calls, which may throw `InterruptedException` instances.

However, if we disable automatic try-catchs, the generated JtxtUML code will contain compilation errors each case a Java function with a `throws` clause listing at least one checked exception type is called, due to unhandled exceptions. As far as I know, there's no other possibility for XtxtUML users to accidentally produce unhandled exception errors, as the grammar doesn't support explicit exception throwing — nor can they eliminate such errors, because neither try-catch blocks, nor `throws` clauses are supported.)

We could re-interpret these kind of errors as implicit action code validation, but I don't really think it's intuitive enough. Of course, we could also implement a validation rule in XtxtUML to disallow problematic method calls. It should be noted that generating a `throws` clause is not a feasible option, as we can't modify the signature of functions overriding JtxtUML methods (e.g. effects or guards).

@nboldi, what do you think?

**Comment by nboldi** [comment]
There should be no `Thread.sleep()` call in the model. Since `Thread` is not a modell class and not part of the API, it cannot be used in the model. Or am I mistaken in some point?

**Comment by djnemeth** [comment]
No, I think you're right, but we should discuss this in the weekly meeting. If we decide to simply disable the aforementioned automatic try-catch generation, the concept of externals should also be adjusted accordingly, see #254.

**Comment by djnemeth** [comment]
The team have decided — considering that calls to Java functions with a `throws` clause are invalid in models anyway — that we shouldn't modify Xtext's automatic try-catch generation. Instead, we shall eliminate the invalid calls from the aforementioned `vending-machine` example, and implement validation rules against such calls as part of the upcoming, comprehensive action code validation rule set.
