### ISSUE TITLE
Documentation for 0.5.0

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#367]
- [x] Update the language guide.
 - [x] Update the diagram language guide.
 - [x] Update the C++ generation guide.  (@nagyandras95)
 - [x] Export and upload the API documentation. (@djnemeth)
 - [x] Export and upload the sample models. (@GregoBalu)
 - [x] Update the website. (@djnemeth)

**Comment by kovacsgabor** [comment]
@GregoBalu and @dobreffandras, please review and update the http://txtuml.inf.elte.hu/wiki/doku.php?id=v050:layout wiki page (I only copied it from the 0.4.0 version and changed the title).

**Comment by kovacsgabor** [comment]
@nagyandras95, please review the C++ generation guide:
http://txtuml.inf.elte.hu/wiki/doku.php?id=v050:userguide#compilation_to_c (I only copied this section from the 0.4.0 version).

**Comment by GregoBalu** [comment]
Diagram lang: DONE.

**Comment by GregoBalu** [comment]
demo.zip uploaded to 050 wiki User Guide page.

**Comment by GregoBalu** [comment]
@nagyandras95 I reviewed the c++ doc, I made a few correction, but it seems OK to me otherwise.

@ELTE-Soft/all The User guide wiki page (maybe other pages as well) contains images linked to previous txtUML version images (for example v020:diag.png). I think we should update these (by simple copy or if the UI changed then with a new one). Or we can leave it be.

**Comment by djnemeth** [comment]
I've re-uploaded the demo examples to include 9a28556. Nice job, everyone!
