### ISSUE TITLE
Migrate to Neon

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#389]
As Neon, the latest Eclipse version is out, we shall investigate what changes are necessary to make txtUML compatible with it.

**Comment by djnemeth** [comment]
Some projects can't be built due to compilation errors. It seems the APIs of Xtext and Papyrus have changed since Mars. I'll take care of the XtxtUML part — @dobreffandras, could you take a look at how serious our problems are on the visualization side?

**Comment by dobreffandras** [comment]
I'll take a look at it this week.

**Comment by djnemeth** [comment]
The team have decided to postpone the migration to version 0.5.1.

**Comment by dobreffandras** [comment]
The Papyrus team introduced the v2.0 in their Neon release and made some API changes. In order to give more headless APIs for the applications that extend/use Papyrus, they separated a bunch of UI dependent parts from the others as written [here](https://wiki.eclipse.org/Papyrus/Migration_Guide/Neon). The IMultiDiagramEditor class was moved to another package ([see](https://wiki.eclipse.org/Papyrus/Migration_Guide/Neon#APIs_Moved_out_of_the_infra.core_Bundle)) and the IPageManager class was also moved to another package ([see](https://wiki.eclipse.org/Papyrus/Migration_Guide/Neon#APIs_Moved_out_of_the_infra.core.sasheditor.di_Bundle)). The *.export.papyrus package were modified to follow these changes. 

The Eclipse runtime also introduced a little change. They made the SubProgressMonitor class deprecated and suggest to use the SubMonitor class. How to migrate is written down in [this article](https://eclipse.org/articles/Article-Progress-Monitors/article.html). I plan to migrate if I'll have some free time.

I did not have a chance to test the modifications because the codebase does not compile yet.

**Comment by zsgyulavari** [comment]
I've created a branch for that here: https://github.com/ELTE-Soft/txtUML/tree/neon-upgrade

And also pushed a version which compiles and does the basics fine (I did not test much since it's unfinisned yet). 

@djnemeth please review the commit https://github.com/ELTE-Soft/txtUML/commit/b16dbd09f5c849b67ae73afd310e7b3b168e85aa especially these two files:
https://github.com/ELTE-Soft/txtUML/compare/neon-upgrade?diff=unified&name=neon-upgrade#diff-88a85eebf71435128e43a70440e821b7
https://github.com/ELTE-Soft/txtUML/compare/neon-upgrade?diff=unified&name=neon-upgrade#diff-88a85eebf71435128e43a70440e821b7

I did not change the `mirrors.target` file yet (waiting for the mirrored packages) so that won't work with the Neon.R release. Please also include the packages specified by the `release.target` file on the mirror server.

**Comment by djnemeth** [comment]
@zsgyulavari, I have checked the files you mentioned, both seem to be correct. I have also copied the required Eclipse repositories to our mirror server and [updated](https://github.com/ELTE-Soft/txtUML/commit/6d43289fcca08fc5907495112131361503d9197c) the mirror target accordingly.

I tried some basic functionality in a runtime Eclipse using the preliminary Neon-upgraded version. It seems the XtxtUML related parts are working correctly, however, I could not generate Papyrus diagrams. After selecting the XMachine3 demo model and its diagram descriptions, clicking on _Finish_ only opened a window titled _Progess Information_ which disappeared immediately.

Regardless of my quick review, comprehensive testing of all possibly affected components is still necessary. The help of @dobreffandras and @nagyandras95 might be required.

**Comment by zsgyulavari** [comment]
Yes, thanks for the review, I still want to double check the SubProcess instances. But the diagram generation worked for me on the train model. I'll try to generate from the other examples.

**Comment by dobreffandras** [comment]
I took a look at the changes you made and I think they're fine. Diagram generation works for me as well. @djnemeth are you sure you've chosen the right description? For _machine3.x.model_ the appropriate description is _machine3.x.XMachine3ClassDiagram_. If you select _machine3.j.Machine3ClassDiagram_ an empty papyrus project will be generated indeed.

Changing the SubProgressMonitor implementations to the SubMonitor ones is not urgent in my opinion because the whole papyrus export plugin is rewritten from scratch on the [new/papyrus-export](https://github.com/ELTE-Soft/txtUML/tree/new/papyrus-export) branch. The branch needs some changes in order to be "release ready" but it will be done soon.

**Note:** The neon migration branch is a little bit outdated as I see, so it needs a merge from master in the near future in order to eliminate the risk of big conflicts.

**Comment by djnemeth** [comment]
I've tried the diagram generation again, and interestingly it works now. According to the persisted values in the wizard I had selected the correct descriptions, so it had to be something else. Hopefully nothing serious, but we'll see if someone manages to reproduce it during the review.

Speaking of which, @zsgyulavari, what's the status of the migration?
