### ISSUE TITLE
Collection support needed, confusing error message

### ISSUE THREAD

**Issue by nboldi** [ELTE-Soft/txtUML#40]
```
Collection<PerformanceTestModel.A> a = this->PerformanceTestModel.AB.a;
```

This instruction produces the following error:
```
Type mismatch: cannot convert from Collection<PerformanceTestModel.A> to Collection<PerformanceTestModel.A>
```
Maybe a java type should not be used that way, but then what is the suggested method to deal with collection types?

**Comment by kovacsgabor** [comment]
Consider waiting for #59.

**Comment by djnemeth** [comment]
The type mismatch is caused by the fact that the LHS is typed as `java.util.Collection<A>` – due to an import of `java.util.Collection` present in the problematic file – whereas the RHS as `hu.elte.txtuml.api.model.Collection<A>`.

The idea behind using simple names in error messages was to make them more readable, but it's clear now that this approach might make error messages confusing. I'm planning to change the implementation such that if the simple names of the mismatching types are equal, fully qualified names are used instead. What do you think?

**Comment by kovacsgabor** [comment]
What is the status of this issue?

**Comment by djnemeth** [comment]
The proposed modification of type mismatch error messages is under development in branch [xtxtuml-validation-fixes](https://github.com/ELTE-Soft/txtUML/compare/xtxtuml-validation-fixes).
