### ISSUE TITLE
Create relationship between Diagram description and model

### ISSUE THREAD

**Issue by dobreffandras** [ELTE-Soft/txtUML#466]
As suggested in #465 the model should be determined from a Diagram description. 

After this feature is implemented the diagram visualization wizard has to be modified: The two browser fields (project, model) should be deleted, only the tree-view has to be present.

**Comment by dobreffandras** [comment]
Maybe the Diagram description itself could provide this feature. (At least for StateMachines as they have a template parameter ModelClass. ClassDiagrams are questionable)

**Comment by dobreffandras** [comment]
A problem can be if the user selects descriptions that are referring to  multiple models

**Comment by kmozsi** [comment]
Assuming this feature is implemented (the model can be determined from a diagram description), what is the expected behavior when the user chooses diagrams from separate models to visualize? 
Maybe an option is grouping the selected descriptions by models and visualize them separately?

The current implementation supposes that the user chooses descriptions from the selected model only, and the others are not visualized.
