### ISSUE TITLE
Collection.add(obj) should add obj to this

### ISSUE THREAD

**Issue by bmartin0121** [ELTE-Soft/txtUML#467]
One of the students from the english software lab pointed out that `c.add(obj)` does not really add `obj` to collection `c` but only to the returned value. Is this intentional? It is logical that `c.add(obj)` modifies the object `c` like in Java.

**Comment by kovacsgabor** [comment]
Read the documentation of `Collection`:
http://txtuml.inf.elte.hu/releases/latest/api/hu/elte/txtuml/api/model/Collection.html

As it says in the very first sentence, the txtUML `Collection` interface is a base interface for **immutable** collections. Therefore yes, it is intentional to implement it like this to make our collections unmodifiable.
