### ISSUE TITLE
Add the vending machine model to the demo examples

### ISSUE THREAD

**Issue by djnemeth** [ELTE-Soft/txtUML#489]
The [vending machine model](https://github.com/ELTE-Soft/txtUML/tree/1109f99d1ff97e56cd79ce72cdcf834c29a47643/examples/demo/vending_machine_separated) in branch [vending-machine-demo-fixes](https://github.com/ELTE-Soft/txtUML/tree/vending-machine-demo-fixes) is likely ready to be released. We have to verify that it's working correctly and it conforms to the standards of our demo examples, then it can be added as a new demo.

**Comment by djnemeth** [comment]
This can be postponed.

**Comment by djnemeth** [comment]
@bmartin0121, what's the status of this model?

**Comment by bmartin0121** [comment]
I didn't change anything since the Ericsson event last summer except the timers. I think it is functionable and only needs a little refactoring to meet the demo standards. Also, there are two unimplemented functions in the GUI (`showDrink` and `showMoney`) but I think they can be omitted as they are only for "eye-candy".
