### ISSUE TITLE
Collections: ordering and uniqueness

### ISSUE THREAD

**Issue by kovacsgabor** [ELTE-Soft/txtUML#59]
Currently, an own `Collection` interface is provided in JtxtUML to contain model objects. Every `assoc` call returns an instance of this interface.

To have a more general solution, the following three collection types could be implemented in JtxtUML, based on rAlf:
- Bag (non-unique, unordered)
- Set (unique, unordered)
- Sequence (non-unique, ordered)

Following this change, all `assoc` calls would return either one of these three collections or a single object (possibly `null`), based on the type of the association end that was queried.

**Comment by devaigergely81** [comment]
Do we have uniqueness and ordering constraints on txtUML association ends already?

The UML standard also lists `OrderedSet` for the unique-ordered case.

Unfortunately, the "typing rules" of an association navigation chain are not trivial:
* If all ends in the chain have multiplicity 1, the result is an object, otherwise a collection. (This is simple.)
* Uniqueness: Navigating through two unique association ends in a chain does not guarantee that the resulting collection is unique. (Eg.: {a-->b1, a-->b2} unique, {b1-->c, b2-->c} unique, but the result is {a-->c, a-->c} non-unique.) There are additional multiplicity constrains in both directions for the chain to guarantee uniqueness.
* Ordering: What is the expected ordering after navigating a chain of length more than one? (Eg. If the ordering is alphabetic for letters and natural ordering for integers and the ordered association instances are <x-->a, x-->b> and <a-->1, a-->3>, <b-->2, b-->4> then is the expected result <1, 3, 2, 4> or <1,2,3,4> ?

**Comment by kovacsgabor** [comment]
I would return <1, 3, 2, 4> with a method to order the elements of the collection. But this is only my personal preference, we need to find a general solution for this problem, of course.

**Comment by kovacsgabor** [comment]
We do not have neither uniqueness nor ordering constraints in txtUML yet. I planned to introduce these along with the new collections as the two problems are strongly connected.

**Comment by kovacsgabor** [comment]
rAlf says that ```Sequence``` is ordered by **position**.

**Comment by kovacsgabor** [comment]
In case of ```x.e``` (where ```x``` is a single item or a collection and ```e``` is an association end), the following table has to be filled:

 x \ e | object | ordered + unique | ordered | unique | general
---- | ---- | ---- | ---- | ---- | ---- | ----
object | object | ordered + unique | ordered | unique | general
ordered + unique | ordered | ordered | ordered | ordered | general
ordered | ordered | ordered | ordered | ordered | general
unique | general | general | general | general | general
general | general | general | general | general | general

(by 'general', I mean an unordered, non-unique collection, like a bag)

Is this correct?
